using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;

namespace Territory.Editor.Bridge
{
    /// <summary>
    /// POCO service — implements ITssEmissionService (Strategy γ).
    /// Accepts a token fetcher callback (slug → value) and writes a .tss file
    /// with :root { --ds-*: value; } block.
    /// DB read layer lives in TssEmitter (bridge entry point) to keep this service testable.
    /// </summary>
    public sealed class TssEmissionService : ITssEmissionService
    {
        readonly Func<string, IReadOnlyList<(string slug, string value)>> _tokenFetcher;

        public TssEmissionService(Func<string, IReadOnlyList<(string slug, string value)>> tokenFetcher)
        {
            _tokenFetcher = tokenFetcher;
        }

        public void EmitTo(string outPath, string themeSlug)
        {
            var dir = Path.GetDirectoryName(outPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            var tokens = _tokenFetcher(themeSlug);
            var sb = new StringBuilder();
            sb.AppendLine($"/* Generated by TssEmissionService — theme: {themeSlug} */");
            sb.AppendLine("/* do not hand-edit; re-run unity:bake-ui to regenerate */");
            sb.AppendLine(":root {");
            foreach (var (slug, value) in tokens)
            {
                var cssVar = SlugToCssVar(slug);
                sb.AppendLine($"    {cssVar}: {value};");
            }
            sb.AppendLine("}");
            File.WriteAllText(outPath, sb.ToString(), Encoding.UTF8);

#if UNITY_EDITOR
            var assetPath = outPath.Replace(Application.dataPath, "Assets");
            UnityEditor.AssetDatabase.ImportAsset(assetPath);
#endif
        }

        static string SlugToCssVar(string slug)
        {
            var sanitized = Regex.Replace(slug, @"[^a-zA-Z0-9\-_]", "-").TrimStart('-');
            return $"--ds-{sanitized}";
        }
    }
}
