using System.IO;
using UnityEngine;

namespace Territory.Editor.Bridge
{
    /// <summary>
    /// POCO service — implements IUxmlEmissionService (Strategy γ).
    /// Translates a PanelRow into a .uxml + .uss file pair under outDir.
    /// Text-format UXML/USS emission; no VisualElement Unity API at this layer.
    /// </summary>
    public sealed class UxmlEmissionService : IUxmlEmissionService
    {
        public void EmitTo(string outDir, PanelRow row)
        {
            if (!Directory.Exists(outDir))
                Directory.CreateDirectory(outDir);

            var uxmlPath = Path.Combine(outDir, $"{row.Slug}.uxml");
            var ussPath = Path.Combine(outDir, $"{row.Slug}.uss");

            File.WriteAllText(uxmlPath, BuildUxml(row));
            File.WriteAllText(ussPath, BuildUss(row));

#if UNITY_EDITOR
            var dataPath = Application.dataPath;
            UnityEditor.AssetDatabase.ImportAsset(uxmlPath.Replace(dataPath, "Assets"));
            UnityEditor.AssetDatabase.ImportAsset(ussPath.Replace(dataPath, "Assets"));
#endif
        }

        static string BuildUxml(PanelRow row) =>
$@"<?xml version=""1.0"" encoding=""utf-8""?>
<ui:UXML
    xmlns:ui=""UnityEngine.UIElements""
    xsi:noNamespaceSchemaLocation=""../../../UIElementsSchema/UIElements.xsd""
    editor-extension-mode=""False"">
  <!-- Panel: {row.Slug} | kind: {row.Kind} | theme: {row.ThemeSlug} -->
  <!-- Generated by UxmlEmissionService — do not hand-edit -->
  <Style src=""project://database/Assets/UI/Themes/{row.ThemeSlug}.tss""/>
  <Style src=""{row.Slug}.uss""/>
  <ui:VisualElement name=""{row.Slug}"" class=""{row.Slug}"">
  </ui:VisualElement>
</ui:UXML>
";

        static string BuildUss(PanelRow row) =>
$@"/* Panel: {row.Slug} | kind: {row.Kind} | theme: {row.ThemeSlug} */
/* Generated by UxmlEmissionService — do not hand-edit */
@import url(""project://database/Assets/UI/Themes/{row.ThemeSlug}.tss"");

.{row.Slug} {{
    background-color: var(--ds-color-bg-card, #313244);
    color: var(--ds-color-text-primary, #cdd6f4);
    padding: var(--ds-space-md, 12px);
}}
";
    }
}
