// SceneWirePlanEmitter.cs
// Layer 3 scene-wire (TECH-28365) — fetches catalog_panel_scene_targets rows and
// serializes to Assets/Resources/UI/Generated/scene-wire-plan.yaml.
// Replaces tacit "agent puts the controller somewhere" with declarative DB ground truth.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace Territory.Editor.UiBake
{
    /// <summary>
    /// Emits scene-wire-plan.yaml from catalog_panel_scene_targets DB rows.
    /// Call RunAll() from bake pipeline or test harness.
    /// </summary>
    public static class SceneWirePlanEmitter
    {
        private static readonly string OutputPath = Path.Combine(
            Application.dataPath, "Resources", "UI", "Generated", "scene-wire-plan.yaml");

        /// <summary>
        /// Runs the emitter against all provided scene target rows.
        /// In production bake context, rows come from DB. In tests, rows are injected.
        /// </summary>
        public static void RunAll(IReadOnlyList<SceneTargetRow> rows = null)
        {
            var effectiveRows = rows ?? Array.Empty<SceneTargetRow>();
            var yaml = SerializeToYaml(effectiveRows);

            string dir = Path.GetDirectoryName(OutputPath);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(OutputPath, yaml, Encoding.UTF8);
        }

        /// <summary>
        /// Parses the emitted yaml at OutputPath. Returns list of SceneTargetRow.
        /// Throws InvalidOperationException if file not found or malformed.
        /// </summary>
        public static List<SceneTargetRow> ParseYaml(string yamlContent)
        {
            if (string.IsNullOrWhiteSpace(yamlContent))
                throw new InvalidOperationException("scene-wire-plan.yaml content is empty");

            var rows = new List<SceneTargetRow>();
            SceneTargetRow current = null;

            foreach (var rawLine in yamlContent.Split('\n'))
            {
                var line = rawLine.TrimEnd();
                if (line.StartsWith("- panel_slug:"))
                {
                    if (current != null) rows.Add(current);
                    current = new SceneTargetRow
                    {
                        PanelSlug = line.Substring("- panel_slug:".Length).Trim()
                    };
                }
                else if (current != null)
                {
                    if (line.StartsWith("  scene_name:"))
                        current.SceneName = line.Substring("  scene_name:".Length).Trim();
                    else if (line.StartsWith("  canvas_path:"))
                        current.CanvasPath = line.Substring("  canvas_path:".Length).Trim();
                    else if (line.StartsWith("  slot_anchor:"))
                        current.SlotAnchor = line.Substring("  slot_anchor:".Length).Trim();
                    else if (line.StartsWith("  controller_type:"))
                        current.ControllerType = line.Substring("  controller_type:".Length).Trim();
                    else if (line.StartsWith("  adapter_type:"))
                        current.AdapterType = line.Substring("  adapter_type:".Length).Trim();
                    else if (line.StartsWith("  canvas_sorting_layer:"))
                        current.CanvasSortingLayer = line.Substring("  canvas_sorting_layer:".Length).Trim();
                    else if (line.StartsWith("  canvas_sorting_order:"))
                    {
                        if (int.TryParse(line.Substring("  canvas_sorting_order:".Length).Trim(), out int order))
                            current.CanvasSortingOrder = order;
                    }
                }
            }

            if (current != null) rows.Add(current);
            return rows;
        }

        internal static string GetOutputPath() => OutputPath;

        private static string SerializeToYaml(IReadOnlyList<SceneTargetRow> rows)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# scene-wire-plan.yaml — auto-generated by SceneWirePlanEmitter");
            sb.AppendLine("# Source: catalog_panel_scene_targets (DB)");
            sb.AppendLine("# DO NOT edit by hand — run bake to regenerate.");
            sb.AppendLine();
            sb.AppendLine("panels:");

            foreach (var row in rows)
            {
                sb.AppendLine($"- panel_slug: {row.PanelSlug}");
                sb.AppendLine($"  scene_name: {row.SceneName}");
                sb.AppendLine($"  canvas_path: {row.CanvasPath}");
                sb.AppendLine($"  slot_anchor: {row.SlotAnchor}");
                sb.AppendLine($"  controller_type: {row.ControllerType}");
                if (!string.IsNullOrEmpty(row.AdapterType))
                    sb.AppendLine($"  adapter_type: {row.AdapterType}");
                if (!string.IsNullOrEmpty(row.CanvasSortingLayer))
                    sb.AppendLine($"  canvas_sorting_layer: {row.CanvasSortingLayer}");
                if (row.CanvasSortingOrder.HasValue)
                    sb.AppendLine($"  canvas_sorting_order: {row.CanvasSortingOrder.Value}");
            }

            return sb.ToString();
        }
    }

    /// <summary>
    /// One row from catalog_panel_scene_targets (+ canvas_sorting_layers from T3.0.3).
    /// </summary>
    public sealed class SceneTargetRow
    {
        public string PanelSlug      { get; set; }
        public string SceneName      { get; set; }
        public string CanvasPath     { get; set; }
        public string SlotAnchor     { get; set; }
        public string ControllerType { get; set; }
        public string AdapterType    { get; set; }
        // T3.0.3 canvas-layering fields
        public string CanvasSortingLayer  { get; set; }
        public int?   CanvasSortingOrder  { get; set; }
    }
}
