// TECH-19975 / game-ui-catalog-bake Stage 9.13
//
// §Red-Stage Proof: HudBar_PanelChildren_AllReferenceDistinctSlugs
//
// Red:  pre-0098 migration, 10 panel_child rows all reference 'hud-bar-budget-button'.
//       Distinct-count == 1 ≠ row-count (10) → test fails.
// Green: post-0098, 16 panel_child rows reference 16 distinct button_ref / label_ref slugs
//        → distinct-count == row-count → test passes.
//
// Uses panels.json snapshot (generated by npm run snapshot:export-game-ui).
// If snapshot absent → Assert.Ignore (not a hard failure; export step may be deferred).

using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using NUnit.Framework;

namespace Territory.Tests.EditMode.UI
{
    public class HudBarDistinctChildrenTest
    {
        private const string SnapshotPath = "Assets/UI/Snapshots/panels.json";

        /// <summary>
        /// All panel_child rows for hud-bar must reference distinct slugs
        /// (no two children share the same button_ref, label_ref, or sprite_ref).
        /// Red: 9.12 stub state has 10× same slug. Green: 9.13 migration gives 16 distinct.
        /// </summary>
        [Test]
        public void HudBar_PanelChildren_AllReferenceDistinctSlugs()
        {
            if (!File.Exists(SnapshotPath))
            {
                Assert.Ignore(
                    $"panels.json missing at {SnapshotPath} — run npm run snapshot:export-game-ui first");
                return;
            }

            string raw = File.ReadAllText(SnapshotPath);

            // Locate hud-bar block — find entry with slug=hud-bar.
            int hudBarIdx = raw.IndexOf("\"slug\": \"hud-bar\"", System.StringComparison.Ordinal);
            if (hudBarIdx < 0)
            {
                Assert.Ignore("panels.json missing hud-bar entry — run migration 0096/0098 + snapshot:export-game-ui");
                return;
            }

            // Slice the hud-bar block (up to the next top-level slug entry).
            int nextSlug = raw.IndexOf("\"slug\":", hudBarIdx + 10, System.StringComparison.Ordinal);
            string hudBlock = nextSlug > hudBarIdx
                ? raw.Substring(hudBarIdx, nextSlug - hudBarIdx)
                : raw.Substring(hudBarIdx);

            // Extract all ref values: button_ref, label_ref, sprite_ref.
            var allRefs = new List<string>();
            allRefs.AddRange(ExtractValues(hudBlock, "button_ref"));
            allRefs.AddRange(ExtractValues(hudBlock, "label_ref"));
            allRefs.AddRange(ExtractValues(hudBlock, "sprite_ref"));

            Assert.IsTrue(allRefs.Count >= 12,
                $"Expected ≥12 child refs in hud-bar snapshot, got {allRefs.Count}. " +
                "Run migration 0098 + npm run snapshot:export-game-ui.");

            // All refs must be distinct.
            var seen = new HashSet<string>();
            var duplicates = new List<string>();
            foreach (var r in allRefs)
            {
                if (!seen.Add(r)) duplicates.Add(r);
            }

            Assert.AreEqual(0, duplicates.Count,
                $"Duplicate refs found in hud-bar panel_child rows: [{string.Join(", ", duplicates)}]. " +
                "Each HUD control must reference a distinct catalog slug. " +
                "Run migration 0098 to replace stub rows with distinct entities.");
        }

        /// <summary>
        /// Verifies hud-bar snapshot has ≥16 total children post-0098
        /// (3 left + 8 center + 5 right = 16).
        /// </summary>
        [Test]
        public void HudBar_Snapshot_Has16ChildrenWithDistinctZones()
        {
            if (!File.Exists(SnapshotPath))
            {
                Assert.Ignore(
                    $"panels.json missing at {SnapshotPath} — run npm run snapshot:export-game-ui first");
                return;
            }

            string raw = File.ReadAllText(SnapshotPath);

            int hudBarIdx = raw.IndexOf("\"slug\": \"hud-bar\"", System.StringComparison.Ordinal);
            if (hudBarIdx < 0)
            {
                Assert.Ignore("panels.json missing hud-bar — run migration 0096/0098 + snapshot:export-game-ui");
                return;
            }

            int nextSlug = raw.IndexOf("\"slug\":", hudBarIdx + 10, System.StringComparison.Ordinal);
            string hudBlock = nextSlug > hudBarIdx
                ? raw.Substring(hudBarIdx, nextSlug - hudBarIdx)
                : raw.Substring(hudBarIdx);

            int leftCount   = CountOccurrences(hudBlock, "\"zone\": \"left\"");
            int centerCount = CountOccurrences(hudBlock, "\"zone\": \"center\"");
            int rightCount  = CountOccurrences(hudBlock, "\"zone\": \"right\"");
            int total       = leftCount + centerCount + rightCount;

            Assert.IsTrue(total >= 16,
                $"Expected ≥16 zone-tagged children in hud-bar, got {total} " +
                $"(left={leftCount} center={centerCount} right={rightCount}). " +
                "Run migration 0098 + snapshot:export-game-ui.");
        }

        // ── helpers ──────────────────────────────────────────────────────────

        private static List<string> ExtractValues(string src, string key)
        {
            var results = new List<string>();
            // Match "key": "value" patterns.
            var pattern = "\"" + key + "\":\\s*\"([^\"]+)\"";
            foreach (Match m in Regex.Matches(src, pattern))
            {
                results.Add(m.Groups[1].Value);
            }
            return results;
        }

        private static int CountOccurrences(string src, string token)
        {
            int count = 0, pos = 0;
            while ((pos = src.IndexOf(token, pos, System.StringComparison.Ordinal)) >= 0)
            {
                count++;
                pos += token.Length;
            }
            return count;
        }
    }
}
